// Copyright (C) 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pod.proto

package pod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_any          Type = 0
	Type_float32      Type = 1
	Type_float64      Type = 2
	Type_uint         Type = 3
	Type_sint         Type = 4
	Type_uint8        Type = 5
	Type_sint8        Type = 6
	Type_uint16       Type = 7
	Type_sint16       Type = 8
	Type_uint32       Type = 9
	Type_sint32       Type = 10
	Type_uint64       Type = 11
	Type_sint64       Type = 12
	Type_bool         Type = 13
	Type_string       Type = 14
	Type_float_array  Type = 15
	Type_double_array Type = 16
	Type_uint_array   Type = 17
	Type_sint_array   Type = 18
	Type_uint8_array  Type = 19
	Type_sint8_array  Type = 20
	Type_uint16_array Type = 21
	Type_sint16_array Type = 22
	Type_uint32_array Type = 23
	Type_sint32_array Type = 24
	Type_uint64_array Type = 25
	Type_sint64_array Type = 26
	Type_bool_array   Type = 27
	Type_string_array Type = 28
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "any",
		1:  "float32",
		2:  "float64",
		3:  "uint",
		4:  "sint",
		5:  "uint8",
		6:  "sint8",
		7:  "uint16",
		8:  "sint16",
		9:  "uint32",
		10: "sint32",
		11: "uint64",
		12: "sint64",
		13: "bool",
		14: "string",
		15: "float_array",
		16: "double_array",
		17: "uint_array",
		18: "sint_array",
		19: "uint8_array",
		20: "sint8_array",
		21: "uint16_array",
		22: "sint16_array",
		23: "uint32_array",
		24: "sint32_array",
		25: "uint64_array",
		26: "sint64_array",
		27: "bool_array",
		28: "string_array",
	}
	Type_value = map[string]int32{
		"any":          0,
		"float32":      1,
		"float64":      2,
		"uint":         3,
		"sint":         4,
		"uint8":        5,
		"sint8":        6,
		"uint16":       7,
		"sint16":       8,
		"uint32":       9,
		"sint32":       10,
		"uint64":       11,
		"sint64":       12,
		"bool":         13,
		"string":       14,
		"float_array":  15,
		"double_array": 16,
		"uint_array":   17,
		"sint_array":   18,
		"uint8_array":  19,
		"sint8_array":  20,
		"uint16_array": 21,
		"sint16_array": 22,
		"uint32_array": 23,
		"sint32_array": 24,
		"uint64_array": 25,
		"sint64_array": 26,
		"bool_array":   27,
		"string_array": 28,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pod_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_pod_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Val:
	//
	//	*Value_Float32
	//	*Value_Float64
	//	*Value_Uint
	//	*Value_Sint
	//	*Value_Uint8
	//	*Value_Sint8
	//	*Value_Uint16
	//	*Value_Sint16
	//	*Value_Uint32
	//	*Value_Sint32
	//	*Value_Uint64
	//	*Value_Sint64
	//	*Value_Bool
	//	*Value_String_
	//	*Value_Float32Array
	//	*Value_Float64Array
	//	*Value_UintArray
	//	*Value_SintArray
	//	*Value_Uint8Array
	//	*Value_Sint8Array
	//	*Value_Uint16Array
	//	*Value_Sint16Array
	//	*Value_Uint32Array
	//	*Value_Sint32Array
	//	*Value_Uint64Array
	//	*Value_Sint64Array
	//	*Value_BoolArray
	//	*Value_StringArray
	Val           isValue_Val `protobuf_oneof:"val"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetVal() isValue_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Value) GetFloat32() float32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Float32); ok {
			return x.Float32
		}
	}
	return 0
}

func (x *Value) GetFloat64() float64 {
	if x != nil {
		if x, ok := x.Val.(*Value_Float64); ok {
			return x.Float64
		}
	}
	return 0
}

func (x *Value) GetUint() uint64 {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint); ok {
			return x.Uint
		}
	}
	return 0
}

func (x *Value) GetSint() int64 {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint); ok {
			return x.Sint
		}
	}
	return 0
}

func (x *Value) GetUint8() uint32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint8); ok {
			return x.Uint8
		}
	}
	return 0
}

func (x *Value) GetSint8() int32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint8); ok {
			return x.Sint8
		}
	}
	return 0
}

func (x *Value) GetUint16() uint32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint16); ok {
			return x.Uint16
		}
	}
	return 0
}

func (x *Value) GetSint16() int32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint16); ok {
			return x.Sint16
		}
	}
	return 0
}

func (x *Value) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *Value) GetSint32() int32 {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint32); ok {
			return x.Sint32
		}
	}
	return 0
}

func (x *Value) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *Value) GetSint64() int64 {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint64); ok {
			return x.Sint64
		}
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Val.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.Val.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetFloat32Array() *Float32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Float32Array); ok {
			return x.Float32Array
		}
	}
	return nil
}

func (x *Value) GetFloat64Array() *Float64Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Float64Array); ok {
			return x.Float64Array
		}
	}
	return nil
}

func (x *Value) GetUintArray() *Uint64Array {
	if x != nil {
		if x, ok := x.Val.(*Value_UintArray); ok {
			return x.UintArray
		}
	}
	return nil
}

func (x *Value) GetSintArray() *Sint64Array {
	if x != nil {
		if x, ok := x.Val.(*Value_SintArray); ok {
			return x.SintArray
		}
	}
	return nil
}

func (x *Value) GetUint8Array() []byte {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint8Array); ok {
			return x.Uint8Array
		}
	}
	return nil
}

func (x *Value) GetSint8Array() *Sint32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint8Array); ok {
			return x.Sint8Array
		}
	}
	return nil
}

func (x *Value) GetUint16Array() *Uint32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint16Array); ok {
			return x.Uint16Array
		}
	}
	return nil
}

func (x *Value) GetSint16Array() *Sint32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint16Array); ok {
			return x.Sint16Array
		}
	}
	return nil
}

func (x *Value) GetUint32Array() *Uint32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint32Array); ok {
			return x.Uint32Array
		}
	}
	return nil
}

func (x *Value) GetSint32Array() *Sint32Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint32Array); ok {
			return x.Sint32Array
		}
	}
	return nil
}

func (x *Value) GetUint64Array() *Uint64Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Uint64Array); ok {
			return x.Uint64Array
		}
	}
	return nil
}

func (x *Value) GetSint64Array() *Sint64Array {
	if x != nil {
		if x, ok := x.Val.(*Value_Sint64Array); ok {
			return x.Sint64Array
		}
	}
	return nil
}

func (x *Value) GetBoolArray() *BoolArray {
	if x != nil {
		if x, ok := x.Val.(*Value_BoolArray); ok {
			return x.BoolArray
		}
	}
	return nil
}

func (x *Value) GetStringArray() *StringArray {
	if x != nil {
		if x, ok := x.Val.(*Value_StringArray); ok {
			return x.StringArray
		}
	}
	return nil
}

type isValue_Val interface {
	isValue_Val()
}

type Value_Float32 struct {
	Float32 float32 `protobuf:"fixed32,1,opt,name=float32,proto3,oneof"`
}

type Value_Float64 struct {
	Float64 float64 `protobuf:"fixed64,2,opt,name=float64,proto3,oneof"`
}

type Value_Uint struct {
	Uint uint64 `protobuf:"varint,3,opt,name=uint,proto3,oneof"`
}

type Value_Sint struct {
	Sint int64 `protobuf:"zigzag64,4,opt,name=sint,proto3,oneof"`
}

type Value_Uint8 struct {
	Uint8 uint32 `protobuf:"varint,5,opt,name=uint8,proto3,oneof"`
}

type Value_Sint8 struct {
	Sint8 int32 `protobuf:"zigzag32,6,opt,name=sint8,proto3,oneof"`
}

type Value_Uint16 struct {
	Uint16 uint32 `protobuf:"varint,7,opt,name=uint16,proto3,oneof"`
}

type Value_Sint16 struct {
	Sint16 int32 `protobuf:"zigzag32,8,opt,name=sint16,proto3,oneof"`
}

type Value_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,9,opt,name=uint32,proto3,oneof"`
}

type Value_Sint32 struct {
	Sint32 int32 `protobuf:"zigzag32,10,opt,name=sint32,proto3,oneof"`
}

type Value_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,11,opt,name=uint64,proto3,oneof"`
}

type Value_Sint64 struct {
	Sint64 int64 `protobuf:"zigzag64,12,opt,name=sint64,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,13,opt,name=bool,proto3,oneof"`
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,14,opt,name=string,proto3,oneof"`
}

type Value_Float32Array struct {
	Float32Array *Float32Array `protobuf:"bytes,15,opt,name=float32_array,json=float32Array,proto3,oneof"`
}

type Value_Float64Array struct {
	Float64Array *Float64Array `protobuf:"bytes,16,opt,name=float64_array,json=float64Array,proto3,oneof"`
}

type Value_UintArray struct {
	UintArray *Uint64Array `protobuf:"bytes,17,opt,name=uint_array,json=uintArray,proto3,oneof"`
}

type Value_SintArray struct {
	SintArray *Sint64Array `protobuf:"bytes,18,opt,name=sint_array,json=sintArray,proto3,oneof"`
}

type Value_Uint8Array struct {
	Uint8Array []byte `protobuf:"bytes,19,opt,name=uint8_array,json=uint8Array,proto3,oneof"`
}

type Value_Sint8Array struct {
	Sint8Array *Sint32Array `protobuf:"bytes,20,opt,name=sint8_array,json=sint8Array,proto3,oneof"`
}

type Value_Uint16Array struct {
	Uint16Array *Uint32Array `protobuf:"bytes,21,opt,name=uint16_array,json=uint16Array,proto3,oneof"`
}

type Value_Sint16Array struct {
	Sint16Array *Sint32Array `protobuf:"bytes,22,opt,name=sint16_array,json=sint16Array,proto3,oneof"`
}

type Value_Uint32Array struct {
	Uint32Array *Uint32Array `protobuf:"bytes,23,opt,name=uint32_array,json=uint32Array,proto3,oneof"`
}

type Value_Sint32Array struct {
	Sint32Array *Sint32Array `protobuf:"bytes,24,opt,name=sint32_array,json=sint32Array,proto3,oneof"`
}

type Value_Uint64Array struct {
	Uint64Array *Uint64Array `protobuf:"bytes,25,opt,name=uint64_array,json=uint64Array,proto3,oneof"`
}

type Value_Sint64Array struct {
	Sint64Array *Sint64Array `protobuf:"bytes,26,opt,name=sint64_array,json=sint64Array,proto3,oneof"`
}

type Value_BoolArray struct {
	BoolArray *BoolArray `protobuf:"bytes,27,opt,name=bool_array,json=boolArray,proto3,oneof"`
}

type Value_StringArray struct {
	StringArray *StringArray `protobuf:"bytes,28,opt,name=string_array,json=stringArray,proto3,oneof"`
}

func (*Value_Float32) isValue_Val() {}

func (*Value_Float64) isValue_Val() {}

func (*Value_Uint) isValue_Val() {}

func (*Value_Sint) isValue_Val() {}

func (*Value_Uint8) isValue_Val() {}

func (*Value_Sint8) isValue_Val() {}

func (*Value_Uint16) isValue_Val() {}

func (*Value_Sint16) isValue_Val() {}

func (*Value_Uint32) isValue_Val() {}

func (*Value_Sint32) isValue_Val() {}

func (*Value_Uint64) isValue_Val() {}

func (*Value_Sint64) isValue_Val() {}

func (*Value_Bool) isValue_Val() {}

func (*Value_String_) isValue_Val() {}

func (*Value_Float32Array) isValue_Val() {}

func (*Value_Float64Array) isValue_Val() {}

func (*Value_UintArray) isValue_Val() {}

func (*Value_SintArray) isValue_Val() {}

func (*Value_Uint8Array) isValue_Val() {}

func (*Value_Sint8Array) isValue_Val() {}

func (*Value_Uint16Array) isValue_Val() {}

func (*Value_Sint16Array) isValue_Val() {}

func (*Value_Uint32Array) isValue_Val() {}

func (*Value_Sint32Array) isValue_Val() {}

func (*Value_Uint64Array) isValue_Val() {}

func (*Value_Sint64Array) isValue_Val() {}

func (*Value_BoolArray) isValue_Val() {}

func (*Value_StringArray) isValue_Val() {}

type Float32Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []float32              `protobuf:"fixed32,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float32Array) Reset() {
	*x = Float32Array{}
	mi := &file_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32Array) ProtoMessage() {}

func (x *Float32Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32Array.ProtoReflect.Descriptor instead.
func (*Float32Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

func (x *Float32Array) GetVal() []float32 {
	if x != nil {
		return x.Val
	}
	return nil
}

type Float64Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []float64              `protobuf:"fixed64,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float64Array) Reset() {
	*x = Float64Array{}
	mi := &file_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float64Array) ProtoMessage() {}

func (x *Float64Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float64Array.ProtoReflect.Descriptor instead.
func (*Float64Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{2}
}

func (x *Float64Array) GetVal() []float64 {
	if x != nil {
		return x.Val
	}
	return nil
}

type Uint32Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []uint32               `protobuf:"varint,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint32Array) Reset() {
	*x = Uint32Array{}
	mi := &file_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32Array) ProtoMessage() {}

func (x *Uint32Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32Array.ProtoReflect.Descriptor instead.
func (*Uint32Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3}
}

func (x *Uint32Array) GetVal() []uint32 {
	if x != nil {
		return x.Val
	}
	return nil
}

type Sint32Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []int32                `protobuf:"zigzag32,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sint32Array) Reset() {
	*x = Sint32Array{}
	mi := &file_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sint32Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint32Array) ProtoMessage() {}

func (x *Sint32Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint32Array.ProtoReflect.Descriptor instead.
func (*Sint32Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{4}
}

func (x *Sint32Array) GetVal() []int32 {
	if x != nil {
		return x.Val
	}
	return nil
}

type Uint64Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []uint64               `protobuf:"varint,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint64Array) Reset() {
	*x = Uint64Array{}
	mi := &file_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Array) ProtoMessage() {}

func (x *Uint64Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Array.ProtoReflect.Descriptor instead.
func (*Uint64Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{5}
}

func (x *Uint64Array) GetVal() []uint64 {
	if x != nil {
		return x.Val
	}
	return nil
}

type Sint64Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []int64                `protobuf:"zigzag64,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sint64Array) Reset() {
	*x = Sint64Array{}
	mi := &file_pod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sint64Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint64Array) ProtoMessage() {}

func (x *Sint64Array) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint64Array.ProtoReflect.Descriptor instead.
func (*Sint64Array) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{6}
}

func (x *Sint64Array) GetVal() []int64 {
	if x != nil {
		return x.Val
	}
	return nil
}

type BoolArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []bool                 `protobuf:"varint,1,rep,packed,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolArray) Reset() {
	*x = BoolArray{}
	mi := &file_pod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArray) ProtoMessage() {}

func (x *BoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArray.ProtoReflect.Descriptor instead.
func (*BoolArray) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{7}
}

func (x *BoolArray) GetVal() []bool {
	if x != nil {
		return x.Val
	}
	return nil
}

type StringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           []string               `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_pod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{8}
}

func (x *StringArray) GetVal() []string {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_pod_proto protoreflect.FileDescriptor

const file_pod_proto_rawDesc = "" +
	"\n" +
	"\tpod.proto\x12\x03pod\"\xd2\b\n" +
	"\x05Value\x12\x1a\n" +
	"\afloat32\x18\x01 \x01(\x02H\x00R\afloat32\x12\x1a\n" +
	"\afloat64\x18\x02 \x01(\x01H\x00R\afloat64\x12\x14\n" +
	"\x04uint\x18\x03 \x01(\x04H\x00R\x04uint\x12\x14\n" +
	"\x04sint\x18\x04 \x01(\x12H\x00R\x04sint\x12\x16\n" +
	"\x05uint8\x18\x05 \x01(\rH\x00R\x05uint8\x12\x16\n" +
	"\x05sint8\x18\x06 \x01(\x11H\x00R\x05sint8\x12\x18\n" +
	"\x06uint16\x18\a \x01(\rH\x00R\x06uint16\x12\x18\n" +
	"\x06sint16\x18\b \x01(\x11H\x00R\x06sint16\x12\x18\n" +
	"\x06uint32\x18\t \x01(\rH\x00R\x06uint32\x12\x18\n" +
	"\x06sint32\x18\n" +
	" \x01(\x11H\x00R\x06sint32\x12\x18\n" +
	"\x06uint64\x18\v \x01(\x04H\x00R\x06uint64\x12\x18\n" +
	"\x06sint64\x18\f \x01(\x12H\x00R\x06sint64\x12\x14\n" +
	"\x04bool\x18\r \x01(\bH\x00R\x04bool\x12\x18\n" +
	"\x06string\x18\x0e \x01(\tH\x00R\x06string\x128\n" +
	"\rfloat32_array\x18\x0f \x01(\v2\x11.pod.Float32ArrayH\x00R\ffloat32Array\x128\n" +
	"\rfloat64_array\x18\x10 \x01(\v2\x11.pod.Float64ArrayH\x00R\ffloat64Array\x121\n" +
	"\n" +
	"uint_array\x18\x11 \x01(\v2\x10.pod.Uint64ArrayH\x00R\tuintArray\x121\n" +
	"\n" +
	"sint_array\x18\x12 \x01(\v2\x10.pod.Sint64ArrayH\x00R\tsintArray\x12!\n" +
	"\vuint8_array\x18\x13 \x01(\fH\x00R\n" +
	"uint8Array\x123\n" +
	"\vsint8_array\x18\x14 \x01(\v2\x10.pod.Sint32ArrayH\x00R\n" +
	"sint8Array\x125\n" +
	"\fuint16_array\x18\x15 \x01(\v2\x10.pod.Uint32ArrayH\x00R\vuint16Array\x125\n" +
	"\fsint16_array\x18\x16 \x01(\v2\x10.pod.Sint32ArrayH\x00R\vsint16Array\x125\n" +
	"\fuint32_array\x18\x17 \x01(\v2\x10.pod.Uint32ArrayH\x00R\vuint32Array\x125\n" +
	"\fsint32_array\x18\x18 \x01(\v2\x10.pod.Sint32ArrayH\x00R\vsint32Array\x125\n" +
	"\fuint64_array\x18\x19 \x01(\v2\x10.pod.Uint64ArrayH\x00R\vuint64Array\x125\n" +
	"\fsint64_array\x18\x1a \x01(\v2\x10.pod.Sint64ArrayH\x00R\vsint64Array\x12/\n" +
	"\n" +
	"bool_array\x18\x1b \x01(\v2\x0e.pod.BoolArrayH\x00R\tboolArray\x125\n" +
	"\fstring_array\x18\x1c \x01(\v2\x10.pod.StringArrayH\x00R\vstringArrayB\x05\n" +
	"\x03val\" \n" +
	"\fFloat32Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\x02R\x03val\" \n" +
	"\fFloat64Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\x01R\x03val\"\x1f\n" +
	"\vUint32Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\rR\x03val\"\x1f\n" +
	"\vSint32Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\x11R\x03val\"\x1f\n" +
	"\vUint64Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\x04R\x03val\"\x1f\n" +
	"\vSint64Array\x12\x10\n" +
	"\x03val\x18\x01 \x03(\x12R\x03val\"\x1d\n" +
	"\tBoolArray\x12\x10\n" +
	"\x03val\x18\x01 \x03(\bR\x03val\"\x1f\n" +
	"\vStringArray\x12\x10\n" +
	"\x03val\x18\x01 \x03(\tR\x03val*\xa4\x03\n" +
	"\x04Type\x12\a\n" +
	"\x03any\x10\x00\x12\v\n" +
	"\afloat32\x10\x01\x12\v\n" +
	"\afloat64\x10\x02\x12\b\n" +
	"\x04uint\x10\x03\x12\b\n" +
	"\x04sint\x10\x04\x12\t\n" +
	"\x05uint8\x10\x05\x12\t\n" +
	"\x05sint8\x10\x06\x12\n" +
	"\n" +
	"\x06uint16\x10\a\x12\n" +
	"\n" +
	"\x06sint16\x10\b\x12\n" +
	"\n" +
	"\x06uint32\x10\t\x12\n" +
	"\n" +
	"\x06sint32\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06uint64\x10\v\x12\n" +
	"\n" +
	"\x06sint64\x10\f\x12\b\n" +
	"\x04bool\x10\r\x12\n" +
	"\n" +
	"\x06string\x10\x0e\x12\x0f\n" +
	"\vfloat_array\x10\x0f\x12\x10\n" +
	"\fdouble_array\x10\x10\x12\x0e\n" +
	"\n" +
	"uint_array\x10\x11\x12\x0e\n" +
	"\n" +
	"sint_array\x10\x12\x12\x0f\n" +
	"\vuint8_array\x10\x13\x12\x0f\n" +
	"\vsint8_array\x10\x14\x12\x10\n" +
	"\fuint16_array\x10\x15\x12\x10\n" +
	"\fsint16_array\x10\x16\x12\x10\n" +
	"\fuint32_array\x10\x17\x12\x10\n" +
	"\fsint32_array\x10\x18\x12\x10\n" +
	"\fuint64_array\x10\x19\x12\x10\n" +
	"\fsint64_array\x10\x1a\x12\x0e\n" +
	"\n" +
	"bool_array\x10\x1b\x12\x10\n" +
	"\fstring_array\x10\x1cBM\n" +
	"\x1fcom.google.gapid.proto.core.podB\x03PodZ%sapelkinav/javadap/jdwp/data/podb\x06proto3"

var (
	file_pod_proto_rawDescOnce sync.Once
	file_pod_proto_rawDescData []byte
)

func file_pod_proto_rawDescGZIP() []byte {
	file_pod_proto_rawDescOnce.Do(func() {
		file_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)))
	})
	return file_pod_proto_rawDescData
}

var file_pod_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pod_proto_goTypes = []any{
	(Type)(0),            // 0: pod.Type
	(*Value)(nil),        // 1: pod.Value
	(*Float32Array)(nil), // 2: pod.Float32Array
	(*Float64Array)(nil), // 3: pod.Float64Array
	(*Uint32Array)(nil),  // 4: pod.Uint32Array
	(*Sint32Array)(nil),  // 5: pod.Sint32Array
	(*Uint64Array)(nil),  // 6: pod.Uint64Array
	(*Sint64Array)(nil),  // 7: pod.Sint64Array
	(*BoolArray)(nil),    // 8: pod.BoolArray
	(*StringArray)(nil),  // 9: pod.StringArray
}
var file_pod_proto_depIdxs = []int32{
	2,  // 0: pod.Value.float32_array:type_name -> pod.Float32Array
	3,  // 1: pod.Value.float64_array:type_name -> pod.Float64Array
	6,  // 2: pod.Value.uint_array:type_name -> pod.Uint64Array
	7,  // 3: pod.Value.sint_array:type_name -> pod.Sint64Array
	5,  // 4: pod.Value.sint8_array:type_name -> pod.Sint32Array
	4,  // 5: pod.Value.uint16_array:type_name -> pod.Uint32Array
	5,  // 6: pod.Value.sint16_array:type_name -> pod.Sint32Array
	4,  // 7: pod.Value.uint32_array:type_name -> pod.Uint32Array
	5,  // 8: pod.Value.sint32_array:type_name -> pod.Sint32Array
	6,  // 9: pod.Value.uint64_array:type_name -> pod.Uint64Array
	7,  // 10: pod.Value.sint64_array:type_name -> pod.Sint64Array
	8,  // 11: pod.Value.bool_array:type_name -> pod.BoolArray
	9,  // 12: pod.Value.string_array:type_name -> pod.StringArray
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pod_proto_init() }
func file_pod_proto_init() {
	if File_pod_proto != nil {
		return
	}
	file_pod_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_Float32)(nil),
		(*Value_Float64)(nil),
		(*Value_Uint)(nil),
		(*Value_Sint)(nil),
		(*Value_Uint8)(nil),
		(*Value_Sint8)(nil),
		(*Value_Uint16)(nil),
		(*Value_Sint16)(nil),
		(*Value_Uint32)(nil),
		(*Value_Sint32)(nil),
		(*Value_Uint64)(nil),
		(*Value_Sint64)(nil),
		(*Value_Bool)(nil),
		(*Value_String_)(nil),
		(*Value_Float32Array)(nil),
		(*Value_Float64Array)(nil),
		(*Value_UintArray)(nil),
		(*Value_SintArray)(nil),
		(*Value_Uint8Array)(nil),
		(*Value_Sint8Array)(nil),
		(*Value_Uint16Array)(nil),
		(*Value_Sint16Array)(nil),
		(*Value_Uint32Array)(nil),
		(*Value_Sint32Array)(nil),
		(*Value_Uint64Array)(nil),
		(*Value_Sint64Array)(nil),
		(*Value_BoolArray)(nil),
		(*Value_StringArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pod_proto_goTypes,
		DependencyIndexes: file_pod_proto_depIdxs,
		EnumInfos:         file_pod_proto_enumTypes,
		MessageInfos:      file_pod_proto_msgTypes,
	}.Build()
	File_pod_proto = out.File
	file_pod_proto_goTypes = nil
	file_pod_proto_depIdxs = nil
}
