// Copyright (C) 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testprotos.proto

package testprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F32           float32                `protobuf:"fixed32,1,opt,name=f32,proto3" json:"f32,omitempty"`
	U32           uint32                 `protobuf:"varint,2,opt,name=u32,proto3" json:"u32,omitempty"`
	S32           int32                  `protobuf:"varint,3,opt,name=s32,proto3" json:"s32,omitempty"`
	Str           string                 `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgA) Reset() {
	*x = MsgA{}
	mi := &file_testprotos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgA) ProtoMessage() {}

func (x *MsgA) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgA.ProtoReflect.Descriptor instead.
func (*MsgA) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{0}
}

func (x *MsgA) GetF32() float32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *MsgA) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *MsgA) GetS32() int32 {
	if x != nil {
		return x.S32
	}
	return 0
}

func (x *MsgA) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type MsgB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F64           float64                `protobuf:"fixed64,1,opt,name=f64,proto3" json:"f64,omitempty"`
	U64           uint64                 `protobuf:"varint,2,opt,name=u64,proto3" json:"u64,omitempty"`
	S64           int64                  `protobuf:"varint,3,opt,name=s64,proto3" json:"s64,omitempty"`
	Bool          bool                   `protobuf:"varint,4,opt,name=bool,proto3" json:"bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgB) Reset() {
	*x = MsgB{}
	mi := &file_testprotos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgB) ProtoMessage() {}

func (x *MsgB) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgB.ProtoReflect.Descriptor instead.
func (*MsgB) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{1}
}

func (x *MsgB) GetF64() float64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *MsgB) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *MsgB) GetS64() int64 {
	if x != nil {
		return x.S64
	}
	return 0
}

func (x *MsgB) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

type MsgC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MsgC_Entry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgC) Reset() {
	*x = MsgC{}
	mi := &file_testprotos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgC) ProtoMessage() {}

func (x *MsgC) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgC.ProtoReflect.Descriptor instead.
func (*MsgC) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{2}
}

func (x *MsgC) GetEntries() []*MsgC_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MsgC_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgC_Entry) Reset() {
	*x = MsgC_Entry{}
	mi := &file_testprotos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgC_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgC_Entry) ProtoMessage() {}

func (x *MsgC_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgC_Entry.ProtoReflect.Descriptor instead.
func (*MsgC_Entry) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MsgC_Entry) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_testprotos_proto protoreflect.FileDescriptor

const file_testprotos_proto_rawDesc = "" +
	"\n" +
	"\x10testprotos.proto\x12\n" +
	"testprotos\"N\n" +
	"\x04MsgA\x12\x10\n" +
	"\x03f32\x18\x01 \x01(\x02R\x03f32\x12\x10\n" +
	"\x03u32\x18\x02 \x01(\rR\x03u32\x12\x10\n" +
	"\x03s32\x18\x03 \x01(\x05R\x03s32\x12\x10\n" +
	"\x03str\x18\x04 \x01(\tR\x03str\"P\n" +
	"\x04MsgB\x12\x10\n" +
	"\x03f64\x18\x01 \x01(\x01R\x03f64\x12\x10\n" +
	"\x03u64\x18\x02 \x01(\x04R\x03u64\x12\x10\n" +
	"\x03s64\x18\x03 \x01(\x03R\x03s64\x12\x12\n" +
	"\x04bool\x18\x04 \x01(\bR\x04bool\"W\n" +
	"\x04MsgC\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.testprotos.MsgC.EntryR\aentries\x1a\x1d\n" +
	"\x05Entry\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05valueB8Z6sapelkinav/javadap/jdwp/data/protoutil/testprotosb\x06proto3"

var (
	file_testprotos_proto_rawDescOnce sync.Once
	file_testprotos_proto_rawDescData []byte
)

func file_testprotos_proto_rawDescGZIP() []byte {
	file_testprotos_proto_rawDescOnce.Do(func() {
		file_testprotos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testprotos_proto_rawDesc), len(file_testprotos_proto_rawDesc)))
	})
	return file_testprotos_proto_rawDescData
}

var file_testprotos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testprotos_proto_goTypes = []any{
	(*MsgA)(nil),       // 0: testprotos.MsgA
	(*MsgB)(nil),       // 1: testprotos.MsgB
	(*MsgC)(nil),       // 2: testprotos.MsgC
	(*MsgC_Entry)(nil), // 3: testprotos.MsgC.Entry
}
var file_testprotos_proto_depIdxs = []int32{
	3, // 0: testprotos.MsgC.entries:type_name -> testprotos.MsgC.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testprotos_proto_init() }
func file_testprotos_proto_init() {
	if File_testprotos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testprotos_proto_rawDesc), len(file_testprotos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testprotos_proto_goTypes,
		DependencyIndexes: file_testprotos_proto_depIdxs,
		MessageInfos:      file_testprotos_proto_msgTypes,
	}.Build()
	File_testprotos_proto = out.File
	file_testprotos_proto_goTypes = nil
	file_testprotos_proto_depIdxs = nil
}
